### ISSUE TITLE
Upload any Software development projects

### ISSUE THREAD

**Issue by anupamdey2001** [anupamdey2001/Hacktoberfest21#1]
You can upload apps, games, websites or anything related to software development projects in this repository.

**Comment by anupamdey2001** [comment]
@deek121477  Yes, you can, just fork it - write some code and make pull request.

**Comment by sumitmohite0501** [comment]
Please assign to me

**Comment by pritambera2000** [comment]
@anupamdey2001 ,  i want to work on it. Please assign me

**Comment by anupamdey2001** [comment]
> @anupamdey2001 please add Hacktoberfest, topic in your repo otherwise it is showing "Project not participating" . or add hacktoberfest-accepcted label in my PR.
It is done
