### ISSUE TITLE
Portfolio Website

### ISSUE THREAD

**Issue by imsushant12** [anupamdey2001/Hacktoberfest21#24]
Responsive portfolio website using HTML, CSS and JavaScript.

**Comment by nemynigam** [comment]
i want to work on it

**Comment by anupamdey2001** [comment]
> i want to work on it

sure:)

**Comment by dayanand-g** [comment]
can you please assign me to this issue??

**Comment by dayanand-g** [comment]
Sorry for the mistake sir

**Comment by VIKAS0264** [comment]
Can you assign me ?

**Comment by VIKAS0264** [comment]
hey @anupamdey2001 I'm having a little confusion do u want me to create a whole new portfolio website or do you want me to edit the existing website.

**Comment by anupamdey2001** [comment]
> hey @anupamdey2001 I'm having a little confusion do u want me to create a whole new portfolio website or do you want me to edit the existing website.

yes create your own portfolio

**Comment by VIKAS0264** [comment]
fine will update you soon.
