### ISSUE TITLE
Upload any competitive programming solutions

### ISSUE THREAD

**Issue by anupamdey2001** [anupamdey2001/Hacktoberfest21#3]
**Preferred [Leetcode ](https://leetcode.com/)Solutions.**

**Comment by rosetanya898** [comment]
can i add my hackerrank solution

**Comment by anupamdey2001** [comment]
@rosetanya898  yes, you can

**Comment by maleeshasilva** [comment]
can I add my hackerrank solutions here?

**Comment by Ameya-1** [comment]
@anupamdey2001 Can I work on this issue

**Comment by anupamdey2001** [comment]
> @anupamdey2001 Can I work on this issue

yes you can
